version: "3.8"

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "3000:3000"
    environment:
      - RETHINKDB_ADDR=rethinkdb:28015
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=notifdb
      - DB_TYPE=rethink # or "mongo" to use MongoDB
    depends_on:
      - rethinkdb
      - mongodb
    restart: unless-stopped
    networks:
      - notification-network

  rethinkdb:
    image: rethinkdb:2.4
    container_name: rethinkdb
    ports:
      - "28015:28015"
      - "8081:8080" # RethinkDB web UI
    restart: unless-stopped
    networks:
      - notification-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge

volumes:
  mongodb_data:
